#!/bin/bash -e

LAMBDA="$1"
LAMBDA_DIR="examples/python/$LAMBDA"

if ! [ -d "$LAMBDA_DIR" ]; then
    echo "The $LAMBDA_DIR directory does not exist"
    exit 1
fi

WORKSPACE=".lambda_package_zip"

(
    rm -rf $WORKSPACE && mkdir -p $WORKSPACE
    cp -r $LAMBDA_DIR $WORKSPACE/lambda
)

(
    REQUIREMENTS="requirements.txt"
    cd $WORKSPACE/lambda

    if [ -f "$REQUIREMENTS" ]; then
        if ! [ -x "$(command -v pip)" ]; then
            echo 'pip is not installed, we need pip to create the deployment package' >&2
            exit 1
        fi

        pip install --platform=manylinux2014_x86_64 --only-binary=:all: \
          -r "$REQUIREMENTS" -q -t .
    fi

    find . -type d -name "__pycache__" -exec rm -rf {} +
    rm -f $REQUIREMENTS

    ZIP_FILE="../lambda.zip"
    zip -rq $ZIP_FILE . && du -h $ZIP_FILE && echo "Created the deployment package"
)

# (
#     cd $WORKSPACE
#     FUNCTION_NAME=$(aws lambda update-function-code \
#         --region us-east-1 \
#         --no-verify-ssl \
#         --function-name "$LAMBDA" \
#         --zip-file fileb://lambda.zip 2>/dev/null | jq .FunctionName)

#     echo $?

#     echo "Lambda code deployed for $FUNCTION_NAME"
#     echo "Waiting for aws to complete the update"
#     aws lambda wait function-updated --function-name $LAMBDA

#     echo "Done"
# )

(
    rm -rf $WORKSPACE
)