#!/bin/bash -e

LAMBDA="$1"
LAMBDA_DIR="examples/python/$LAMBDA"

if ! [ -d "$LAMBDA_DIR" ]; then
    echo "The $LAMBDA_DIR directory does not exist"
    exit 1
fi

DIRECTORY_TO_DEPLOY_FULL_PATH=$LAMBDA_DIR

WORKSPACE=".deployment_temporary_packing_workspace"
PACKAGE_FILE_NAME="package.zip"

PACKAGE_TYPE="lambda"
# lambda / layer

PACKAGE_DIRECTORY="$WORKSPACE/package_directory"
INSTALL_DIRECTORY="$PACKAGE_DIRECTORY"
if [ "$PACKAGE_TYPE" == "layer" ]; then
    INSTALL_DIRECTORY="$PACKAGE_DIRECTORY/python"
fi

(
    rm -rf $WORKSPACE && mkdir -p $INSTALL_DIRECTORY
    rm -rf $INSTALL_DIRECTORY && cp -r $DIRECTORY_TO_DEPLOY_FULL_PATH $INSTALL_DIRECTORY
)

(
    cd $INSTALL_DIRECTORY

    REQUIREMENTS="requirements.txt"
    CUSTOM_INSTALL="custom/install"

    if [[ -f $CUSTOM_INSTALL ]]; then
        echo "Found custom install script, using it to install the dependencies"
        . $CUSTOM_INSTALL
    else
        if [ -f $REQUIREMENTS ]; then
        if ! [ -x "$(command -v pip)" ]; then
            echo 'pip is not installed, we need pip to create the deployment package' >&2
            exit 1
        fi

        pip install --platform=manylinux2014_x86_64 --only-binary=:all: \
            -r $REQUIREMENTS -t .
        fi
    fi

    find . -type d -name "__pycache__" -exec rm -rf {} +
    rm -f $REQUIREMENTS
    rm -rf custom
)

(
    cd $PACKAGE_DIRECTORY

    ZIP_FILE="../$PACKAGE_FILE_NAME"
    zip -rq $ZIP_FILE .

    du -h $ZIP_FILE
    echo "Created the deployment package $ZIP_FILE"
)

PACKAGE_FILE_PATH="$WORKSPACE/$PACKAGE_FILE_NAME"

(
    cd $WORKSPACE
    FUNCTION_NAME=$(aws lambda update-function-code \
        --region us-east-1 \
        --no-verify-ssl \
        --function-name "$LAMBDA" \
        --zip-file fileb://$PACKAGE_FILE_PATH 2>/dev/null | jq .FunctionName)

    echo $?

    echo "Lambda code deployed for $FUNCTION_NAME"
    echo "Waiting for aws to complete the update"
    aws lambda wait function-updated --function-name $LAMBDA

    echo "Done"
)

(
    rm -rf $WORKSPACE
)