#!/bin/bash

ALLOWED_BRANCHE="master"
COMMIT_MESSAGE="Updated the github-action-example"

ACTIVE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$ACTIVE_BRANCH" != "$ALLOWED_BRANCHE" ]; then
  echo "Error: You can only commit to the '$ALLOWED_BRANCHE' branch"
  echo "Current active branch: '$ACTIVE_BRANCH'"
  exit 1
fi

git reset --soft HEAD~
git add -A && git commit -m "$COMMIT_MESSAGE"
git push -f

echo
echo -e "Wait for a second ...\n" && sleep 1

echo "Changes in the last commit:"
git diff HEAD~1 HEAD --name-only && echo

git log -2