name: A01_basic
on: workflow_dispatch

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: |
          echo "jq is installed by default"
          jq --version
      - run: pwd
      - run: ls -la
