name: A01_basic
on: workflow_dispatch

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: |
          echo "jq is installed by default"
          jq --version
      - run: pwd
      - run: ls -la
      - run: |
          echo "::notice:: This is a notice"
          echo "::warning:: This is a warning"
          echo "::error:: This is an error"
