name: A08_lambda_and_layers_deployment
env:
  PRODUCT_NAME: A08_lambda_and_layers_deployment
  WORKING_DIRECTORY: examples/python
  DEFAULT_PYTHON_VERSION: 3.14

on:
  push:
    branches: [ OK ]
    paths:
      - "**"

  workflow_dispatch:
    inputs:
      branch-to-deploy:
        type: choice
        description: "Choose the branch to deploy"
        required: true
        options: [ master, release, develop ]
        default: master
      workflow-dispatch-input-directories:
        type: string
        description: |
          Comma separated Lambda folder names,
          leave empty to deploy changes in the last pull request
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch-to-deploy || github.ref_name }}
  cancel-in-progress: false

jobs:
  deployment_launcher:
    name: Deployment Launcher
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.launch_jobs.outputs.branches }}
      directories: ${{ steps.launch_jobs.outputs.directories }}
    steps:
      - name: Triggered by ${{ github.event_name }} event
        run: |
          BRANCH_NAME="${{ inputs.branch-to-deploy || github.ref_name }}"
          WORKFLOW_DISPATCH_INPUT_DIRECTORIES="$(echo "${{ inputs.workflow-dispatch-input-directories }}" | xargs)"

          echo "::notice::Branch to deploy: $BRANCH_NAME"
          echo "::notice::The workflow_dispatch input directory names: ${WORKFLOW_DISPATCH_INPUT_DIRECTORIES:-NA}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "WORKFLOW_DISPATCH_INPUT_DIRECTORIES=$WORKFLOW_DISPATCH_INPUT_DIRECTORIES" >> $GITHUB_ENV

      - name: Check out
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 2

      - name: Get directories from workflow_dispatch input
        if: env.WORKFLOW_DISPATCH_INPUT_DIRECTORIES != ''
        run: |
          cd "${{ env.WORKING_DIRECTORY }}"

          IFS=',' read -ra INPUT_DIRS <<< "${WORKFLOW_DISPATCH_INPUT_DIRECTORIES}"
          SELECTED_DIRS=()
          for d in "${INPUT_DIRS[@]}"; do
            d="$(echo "$d" | xargs)"
            if [[ -n "$d" ]]; then

                if [[ (! -d "$d") || ("$d" == */*) || ("$d" == *.*) ]]; then
                  echo "::warning::Directory name '$d' is not valid and will be ignored"
                  continue
                fi

                SELECTED_DIRS+=("$d")
            fi
          done

          SELECTED_DIRS="$(printf "%s\n" "${SELECTED_DIRS[@]}" | sort -u)"
          if [[ -z "$SELECTED_DIRS" ]]; then
            SELECTED_DIRS=()
          else
            mapfile -t SELECTED_DIRS <<<"$SELECTED_DIRS"
          fi

          if [[ ${#SELECTED_DIRS[@]} == 0 ]]; then
            msg="No valid directory in the input"
            msg="$msg, No deployment launched"
            msg="$msg. Please put in the correct directory names"

            echo "::notice::$msg"
          fi

          SELECTED_DIRS="$(jq -n '$ARGS.positional' -c '.' --args "${SELECTED_DIRS[@]}")"
          echo "SELECTED_DIRS=$SELECTED_DIRS" >> $GITHUB_ENV

      - name: Get directories from the last git commit
        if: env.WORKFLOW_DISPATCH_INPUT_DIRECTORIES == ''
        run: |
          echo "::notice::Auto-detecting directories in the last commit in the '$BRANCH_NAME' branch"

          cd "${{ env.WORKING_DIRECTORY }}"

          mapfile -t MODIFIED_DIRECTORIES <<< "$(git diff --relative --name-only HEAD^1 HEAD | grep / | cut -d/ -f1 | sort -u)"
          SELECTED_DIRS=()
          for d in "${MODIFIED_DIRECTORIES[@]}"; do
            d="$(echo "$d" | xargs)"
            if [[ (-n "$d") && (-d "$d") ]]; then
              SELECTED_DIRS+=("$d")
            fi
          done

          if [[ ${#SELECTED_DIRS[@]} == 0 ]]; then
            msg="No directory change detected in the last commit"
            msg="$msg, No deployment launched"
            msg="$msg. But you can always force a deployment by manually starting the workflow and providing the directory names"

            echo "::notice::$msg"
          fi

          SELECTED_DIRS="$(jq -n '$ARGS.positional' -c '.' --args "${SELECTED_DIRS[@]}")"
          echo "SELECTED_DIRS=$SELECTED_DIRS" >> $GITHUB_ENV

      - name: Launch jobs
        id: launch_jobs
        run: |
          branches=("${{ env.BRANCH_NAME }}")
          branches="$(jq -n '$ARGS.positional' -c '.' --args "${branches[@]}")"

          echo "branches=$branches" >> $GITHUB_OUTPUT
          echo "directories=$SELECTED_DIRS" >> $GITHUB_OUTPUT

  deployment:
    name: Deployment
    needs: deployment_launcher
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.deployment_launcher.outputs.branches) }}
        directory: ${{ fromJson(needs.deployment_launcher.outputs.directories) }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    if: ${{ needs.deployment_launcher.outputs.directories != '[]' }}
    steps:
      - name: Starting deployment for ${{ matrix.directory }} on ${{ matrix.branch }}
        run: |
          BRANCH_NAME="${{ matrix.branch }}"
          DIRECTORY_TO_DEPLOY="${{ matrix.directory }}"

          declare -A branch_env_map=(
            ["develop"]="dev"
            ["release"]="qa"
            ["master"]="prod"
          )

          DEPLOY_ENV="${branch_env_map[$BRANCH_NAME]}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV
          echo "DIRECTORY_TO_DEPLOY=$DIRECTORY_TO_DEPLOY" >> $GITHUB_ENV
          echo "DIRECTORY_TO_DEPLOY_FULL_PATH=${{ env.WORKING_DIRECTORY }}/$DIRECTORY_TO_DEPLOY" >> $GITHUB_ENV

      - name: Check out
        uses: actions/checkout@v6
        with:
          ref: "${{ env.BRANCH_NAME }}"
          sparse-checkout: "${{ env.DIRECTORY_TO_DEPLOY_FULL_PATH }}"
          fetch-depth: 1

      - name: Check if custom python version specified
        run: |
          if [[ ! -d "$DIRECTORY_TO_DEPLOY_FULL_PATH" ]]; then
            echo "$DIRECTORY_TO_DEPLOY_FULL_PATH does not exist" >&2
            exit 1
          fi

          cd "$DIRECTORY_TO_DEPLOY_FULL_PATH"

          version_file="custom/VERSION.txt"
          if [[ -f "$version_file" ]]; then
            PYTHON_VERSION="$(cat $version_file | xargs)"
            PYTHON_VERSION="${PYTHON_VERSION,,}"
            PYTHON_VERSION="${PYTHON_VERSION#python}"

            echo "Custom python version $PYTHON_VERSION will be used"
          else
            PYTHON_VERSION="${{ env.DEFAULT_PYTHON_VERSION }}"

            echo "Default python version $PYTHON_VERSION will be used"
          fi

          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: python --version

      - name: package deployment artifact
        run: |
          package_type="lambda"
          # lambda / layer

          WORKSPACE=".deployment_artifact_workspace"
          PACKAGE_FILE_NAME="artifact.zip"

          PACKAGE_DIRECTORY="$WORKSPACE/package_directory"
          INSTALL_DIRECTORY="$PACKAGE_DIRECTORY"
          if [ "$package_type" == "layer" ]; then
              INSTALL_DIRECTORY="$PACKAGE_DIRECTORY/python"
          fi

          (
            rm -rf $WORKSPACE && mkdir -p $INSTALL_DIRECTORY
            rm -rf $INSTALL_DIRECTORY && cp -r $DIRECTORY_TO_DEPLOY_FULL_PATH $INSTALL_DIRECTORY
          )

          (
            cd $INSTALL_DIRECTORY

            REQUIREMENTS="requirements.txt"
            CUSTOM_INSTALL="custom/install"

            if [[ -f $CUSTOM_INSTALL ]]; then
                echo "Found custom install script, using it to install the dependencies"
                . $CUSTOM_INSTALL
            else
                if [ -f $REQUIREMENTS ]; then
                  if ! [ -x "$(command -v pip)" ]; then
                      echo 'pip is not installed, we need pip to create the deployment package' >&2
                      exit 1
                  fi

                  pip install --platform=manylinux2014_x86_64 --only-binary=:all: \
                      -r $REQUIREMENTS -t .
                fi
            fi

            find . -type d -name "__pycache__" -exec rm -rf {} +
            rm -f $REQUIREMENTS
            rm -rf custom
          )

          (
            cd $PACKAGE_DIRECTORY

            ZIP_FILE="../$PACKAGE_FILE_NAME"
            zip -rq $ZIP_FILE .

            du -h $ZIP_FILE
            echo "Created the deployment package $ZIP_FILE"
          )

          echo "PACKAGE_FILE_PATH=$WORKSPACE/$PACKAGE_FILE_NAME" >> $GITHUB_ENV

      - name: Deployment
        run: |
          
          ls -l $PACKAGE_FILE_PATH
          du -h $PACKAGE_FILE_PATH
