name: A08_matrix
env:
  PRODUCT_NAME: A08_matrix
  WORKING_DIRECTORY: .

on:
  push:
    branches: [OK]
    paths:
      - "**"

  workflow_dispatch:
    inputs:
      branch-to-deploy:
        type: choice
        description: "Choose the branch to deploy"
        required: true
        options: [master]
        default: master
      lambda_names:
        type: string
        description: | 
          Comma separated Lambda folder names,
          leave empty to deploy changes in the last PR
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch-to-deploy || github.ref_name }}
  cancel-in-progress: false

jobs:
  deployment_launcher:
    name: Deployment Launcher
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.launch_jobs.outputs.branches }}
      directories: ${{ steps.launch_jobs.outputs.directories }}
    steps:
      - name: Triggered by ${{ github.event_name }} event
        run: |
          BRANCH_NAME="${{ inputs.branch-to-deploy || github.ref_name }}"
          INPUT_LAMBDA_NAMES="$(echo "${{ inputs.lambda_names }}" | xargs)"

          echo "Branch to deploy: $BRANCH_NAME"
          echo "Lambda names: ${INPUT_LAMBDA_NAMES:-NA}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "INPUT_LAMBDA_NAMES=$INPUT_LAMBDA_NAMES" >> $GITHUB_ENV

      - name: Check out
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 2

      - name: Get lambda directories from github action input
        if: env.INPUT_LAMBDA_NAMES != ''
        run: |
          IFS=',' read -ra INPUT_LAMBDA_DIRS <<< "${INPUT_LAMBDA_NAMES}"
          LAMBDA_DIRS=()
          for d in "${INPUT_LAMBDA_DIRS[@]}"; do
            d="$(echo "$d" | xargs)"
            if [[ -n "$d" ]]; then
                LAMBDA_DIRS+=("$d")
            fi
          done

          # This is fine as INPUT_LAMBDA_NAMES is non-empty when the step runs
          mapfile -t LAMBDA_DIRS <<<"$(printf "%s\n" "${LAMBDA_DIRS[@]}" | uniq)"

          LAMBDA_DIRS="$(jq -n '$ARGS.positional' -c '.' --args "${LAMBDA_DIRS[@]}")"
          echo "LAMBDA_DIRS=$LAMBDA_DIRS" >> $GITHUB_ENV

      - name: Get lambda directories from the last git commit
        if: env.INPUT_LAMBDA_NAMES == ''
        run: |
          cd ${{ env.WORKING_DIRECTORY }}

          mapfile -t DIRECTORIES <<< "$(git diff --relative --name-only HEAD^1 HEAD | grep / | cut -d/ -f1 | sort -u)"
          LAMBDA_DIRS=()
          for d in "${DIRECTORIES[@]}"; do
            d="$(echo "$d" | xargs)"
            if [[ -n "$d" ]]; then
              LAMBDA_DIRS+=("$d")
            fi
          done

          LAMBDA_DIRS="$(jq -n '$ARGS.positional' -c '.' --args "${LAMBDA_DIRS[@]}")"
          echo "LAMBDA_DIRS=$LAMBDA_DIRS" >> $GITHUB_ENV

      - name: Launch jobs
        id: launch_jobs
        run: |
          branches=("${{ env.BRANCH_NAME }}")
          branches="$(jq -n '$ARGS.positional' -c '.' --args "${branches[@]}")"

          echo "branches=$branches" >> $GITHUB_OUTPUT
          echo "directories=$LAMBDA_DIRS" >> $GITHUB_OUTPUT

  deployment:
    name: Deployment
    needs: deployment_launcher
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.deployment_launcher.outputs.branches) }}
        directory: ${{ fromJson(needs.deployment_launcher.outputs.directories) }}
    runs-on: ubuntu-latest
    if: ${{ needs.deployment_launcher.outputs.directories != '[]' }}
    steps:
      - name: Starting deployment job for directory ${{ matrix.directory }} on branch ${{ matrix.branch }}
        run: |
          echo "directory=${{ matrix.directory }}">> $GITHUB_ENV
          echo "branch=${{ matrix.branch }}">> $GITHUB_ENV

      - name: Check out
        uses: actions/checkout@v6
        with:
          ref: "${{ env.branch }}"
          sparse-checkout: "${{ env.directory }}"
          fetch-depth: 1

      - name: Run tests
        run: |

          if [[ ! -d "$directory" ]]; then
            echo "Directory '$directory' does not exist"
            exit 1
          fi

          cd "$directory"

          pwd && ls -la

          echo "Running tests for directory: $directory on branch: $branch"
