name: A09_concurrency

on:
  push:
    branches: [master]
    paths:
      - "**"

  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: "Git branch"
        required: true
        options: [master, release, develop]
        default: master

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch || github.ref_name }}
  cancel-in-progress: false

jobs:
  what_are_we_receiving:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ inputs.branch || github.ref_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"

          echo "Sleeping for 30 seconds to test concurrency"
          sleep 30
